// Generated by scripts/import-design.mjs. Do not edit by hand.
export const screens = [
  {
    "file": "Login.html",
    "route": "/login",
    "group": "Website",
    "label": "Portal Login",
    "id": "login",
    "title": "Portal Login — Sharda Public School"
  },
  {
    "file": "Student Portal.html",
    "route": "/student-portal",
    "group": "Student Portal",
    "label": "Dashboard",
    "id": "student-portal",
    "title": "Student Portal — Sharda Public School"
  },
  {
    "file": "Student Portal - Calendar.html",
    "route": "/student-portal/calendar",
    "group": "Student Portal",
    "label": "Calendar",
    "id": "student-portal--calendar",
    "title": "School Calendar — Student Portal · Sharda Public School"
  },
  {
    "file": "Student Portal - Messages.html",
    "route": "/student-portal/messages",
    "group": "Student Portal",
    "label": "Messages",
    "id": "student-portal--messages",
    "title": "Messages — Student Portal · Sharda Public School"
  },
  {
    "file": "Student Portal - Settings.html",
    "route": "/student-portal/settings",
    "group": "Student Portal",
    "label": "Settings",
    "id": "student-portal--settings",
    "title": "Settings — Student Portal · Sharda Public School"
  },
  {
    "file": "Teacher Portal.html",
    "route": "/teacher-portal",
    "group": "Teacher Portal",
    "label": "Dashboard",
    "id": "teacher-portal",
    "title": "Teacher Portal — Sharda Public School"
  },
  {
    "file": "Teacher Portal - Calendar.html",
    "route": "/teacher-portal/calendar",
    "group": "Teacher Portal",
    "label": "Calendar",
    "id": "teacher-portal--calendar",
    "title": "School Calendar — Teacher Portal · Sharda Public School"
  },
  {
    "file": "Teacher Portal - Messages.html",
    "route": "/teacher-portal/messages",
    "group": "Teacher Portal",
    "label": "Messages",
    "id": "teacher-portal--messages",
    "title": "Messages — Teacher Portal · Sharda Public School"
  },
  {
    "file": "Teacher Portal - Settings.html",
    "route": "/teacher-portal/settings",
    "group": "Teacher Portal",
    "label": "Settings",
    "id": "teacher-portal--settings",
    "title": "Settings — Teacher Portal · Sharda Public School"
  },
  {
    "file": "Parent Portal.html",
    "route": "/parent-portal",
    "group": "Parent Portal",
    "label": "Dashboard",
    "id": "parent-portal",
    "title": "Parent Portal — Sharda Public School"
  },
  {
    "file": "Admin Portal.html",
    "route": "/admin-portal",
    "group": "Admin Portal",
    "label": "Dashboard",
    "id": "admin-portal",
    "title": "Admin Portal — Sharda Public School"
  },
  {
    "file": "Feature Documentation.html",
    "route": "/feature-documentation",
    "group": "Docs",
    "label": "Feature Documentation",
    "id": "feature-documentation",
    "title": "Feature Documentation — Sharda Public School Website"
  }
] as const;

export const loaders: Record<string, () => Promise<{ title: string; html: string }>> = {
  "login": () => import("./login"),
  "student-portal": () => import("./student-portal"),
  "student-portal--calendar": () => import("./student-portal--calendar"),
  "student-portal--messages": () => import("./student-portal--messages"),
  "student-portal--settings": () => import("./student-portal--settings"),
  "teacher-portal": () => import("./teacher-portal"),
  "teacher-portal--calendar": () => import("./teacher-portal--calendar"),
  "teacher-portal--messages": () => import("./teacher-portal--messages"),
  "teacher-portal--settings": () => import("./teacher-portal--settings"),
  "parent-portal": () => import("./parent-portal"),
  "admin-portal": () => import("./admin-portal"),
  "feature-documentation": () => import("./feature-documentation"),
};
